DROP TABLE IF EXISTS artistas;
DROP TABLE IF EXISTS personal;
DROP TABLE IF EXISTS instalaciones;
DROP TABLE IF EXISTS gira;
DROP TABLE IF EXISTS conciertos;
DROP TABLE IF EXISTS conciertos_tienen_artistas;
DROP TABLE IF EXISTS entradas;
DROP TABLE IF EXISTS personal_trabaja_conciertos;

CREATE TABLE artistas (
  NOMBRE varchar(40) NOT NULL,
  PAÍS_ORIGEN varchar(45) NOT NULL,
  SUELDO int NOT NULL,
  GÉNERO_MUSICAL varchar(45) NOT NULL,
  AGENTE varchar(45) NOT NULL,
  PRIMARY KEY (NOMBRE)
);

CREATE TABLE personal (
  ID_PERSONAL int NOT NULL,
  NOMBRE varchar(45) NOT NULL,
  APELLIDOS varchar(45) NOT NULL,
  NIF varchar(10) NOT NULL,
  FECHA_NACIMIENTO date NOT NULL,
  TELEFONO varchar(10) NOT NULL,
  SUELDO int NOT NULL,
  PRIMARY KEY (ID_PERSONAL)
);


CREATE TABLE instalaciones (
  ID_INSTALACIONES int NOT NULL,
  NOMBRE varchar(50) NOT NULL,
  PAIS varchar(45) NOT NULL,
  DIRECCION varchar(45) NOT NULL,
  CAPACIDAD int NOT NULL,
  PRIMARY KEY (ID_INSTALACIONES)
);

CREATE TABLE gira (
  NOMBRE varchar(70) NOT NULL,
  ARTISTAS_NOMBRE varchar(40) NOT NULL,
  PRIMARY KEY (NOMBRE),
  CONSTRAINT FK_GIRA1 FOREIGN KEY (ARTISTAS_NOMBRE) REFERENCES `BBDD FINAL`.artistas(NOMBRE)
);

CREATE TABLE conciertos (
  FECHA date NOT NULL,
  DURACIÓN varchar(10) NOT NULL,
  ID_INSTALACIÓN int NOT NULL,
  GIRA_NOMBRE varchar(70) NOT NULL,
  PRIMARY KEY (GIRA_NOMBRE, FECHA),
  FOREIGN KEY (GIRA_NOMBRE) REFERENCES gira(NOMBRE),
  FOREIGN KEY (ID_INSTALACIÓN) REFERENCES instalaciones(ID_INSTALACIONES)
);

CREATE TABLE conciertos_tienen_artistas (
  CONCIERTOS_GIRA_NOMBRE varchar(70) NOT NULL,
  CONCIERTOS_FECHA date NOT NULL,
  ARTISTAS_NOMBRE varchar(40) NOT NULL,
  PRIMARY KEY (CONCIERTOS_GIRA_NOMBRE, CONCIERTOS_FECHA, ARTISTAS_NOMBRE),
  FOREIGN KEY (ARTISTAS_NOMBRE) REFERENCES artistas (NOMBRE),
  FOREIGN KEY (CONCIERTOS_GIRA_NOMBRE, CONCIERTOS_FECHA) REFERENCES conciertos(GIRA_NOMBRE, FECHA)
);

CREATE TABLE entradas (
  TIPO varchar(10) NOT NULL,
  Nº_ENTRADAS int NOT NULL,
  PRECIO int unsigned NOT NULL,
  ZONA varchar(40) DEFAULT NULL,
  CÓDIGO_DE_ENTRADA varchar(45) DEFAULT NULL,
  CONCIERTOS_GIRA_NOMBRE varchar(70) NOT NULL,
  CONCIERTOS_FECHA date NOT NULL,
  PRIMARY KEY (TIPO,CONCIERTOS_GIRA_NOMBRE,CONCIERTOS_FECHA),
  CONSTRAINT fk_ENTRADAS_CONCIERTOS1 FOREIGN KEY (CONCIERTOS_GIRA_NOMBRE, CONCIERTOS_FECHA) REFERENCES conciertos(GIRA_NOMBRE, FECHA)
);

CREATE TABLE personal_trabaja_conciertos (
  PERSONAL_ID_PERSONAL int NOT NULL,
  CONCIERTOS_GIRA_NOMBRE varchar(70) NOT NULL,
  CONCIERTOS_FECHA date NOT NULL,
  PRIMARY KEY (PERSONAL_ID_PERSONAL,CONCIERTOS_GIRA_NOMBRE,CONCIERTOS_FECHA),
  FOREIGN KEY (CONCIERTOS_GIRA_NOMBRE, CONCIERTOS_FECHA) REFERENCES conciertos(GIRA_NOMBRE, FECHA),
  FOREIGN KEY (PERSONAL_ID_PERSONAL) REFERENCES personal(ID_PERSONAL)
);
